
# Generated by Django 3.1.2 on 2020-10-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            'Task',
            'data',
            models.TextField(verbose_name='Дата'),
        ),
    ]
